### ISSUE TITLE
Feature request: Downloadable png in indexed format matching quantized output, or text output of quantized palette

### ISSUE THREAD

**Issue by bbbbbr** [rilden/tiledpalettequant#2]
Love the tool and find it useful. I have a feature request-

It would be very useful if the resulting downloadable image was in indexed palette mode instead of RGB, and for the indexed palette to match the resulting quantized palette (and for each tile to use the correct indexes of that palette). That way it could be used with tools that only operate on indexed palettes and which don't have their own quantization step. (Edit: looks like canvas may only operate in RGBA mode, so maybe this output wouldn't be easy to generate.)

Alternatively, and probably easier: Provide version of the resulting palette in a text based RGB format (maybe either numeric or classic html hex style `#RRGGBB`) which could be used in a simple remapping step.

**Comment by rilden** [comment]
When you click on the output image, it will now be saved as an indexed bmp.

**Comment by bbbbbr** [comment]
Thank you!
