### ISSUE TITLE
OK to make a console version?

### ISSUE THREAD

**Issue by bbbbbr** [rilden/tiledpalettequant#4]
I know this project is under an MIT license, but I thought it would be polite to ask - would it be ok if I tried to convert this into a console based tool (rewrite in C probably) for Linux/Windows/Mac? It would retain the existing license and attribution. No worries if you'd rather not.

It's convenient to have the web app, but it doesn't integrate as easily with build toolchains.

**Comment by rilden** [comment]
You can make a console version, I don't mind.

**Comment by bbbbbr** [comment]
Thank you!

**Comment by pappleby** [comment]
FYI, made a nodeJS [version](https://github.com/pappleby/tiledpalettequantcli)! (Very handy to be able to experiment with the web version to pin down the right parameters before batch converting in the console)

**Comment by bbbbbr** [comment]
Finally did the console version, ported to c++. Seems to be working more or less correctly now.

https://github.com/bbbbbr/tilepalquant/releases/

Thanks again for making this tool, it continues to have some of the best conversion output I've seen.
